=== jwbutler/cyoa/src/scene.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "scene",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "actions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "adds": {
            "type": "object",
            "properties": {
              "items": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "remove": {
            "type": "object",
            "properties": {
              "items": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "goto": {
            "room": "string"
          }
        },
        "required": [ "text" ]
      }
    },
    "condition": {
      "type": "object",
      "properties": {
        "requires": {
          "type": "object",
          "properties": {
            "items": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "forbids": {
          "type": "object",
          "properties": {
            "items": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "required": [ "id", "name", "description" ]
}

=== jwbutler/cyoa/src/rooms.json
[
  {
    "id": "backyard",
    "name": "Backyard",
    "description": "You're in the backyard.  There's a swing set on one end of the yard, and a small shed on another side.",
    "actions": [
      {
        "text": "Go back inside",
        "ref": "dining_room"
      },
      {
        "text": "Go in the shed",
        "ref": "shed"
      },
      {
        "text": "Go to the driveway",
        "ref": "driveway"
      }
    ]
  },
  {
    "id": "den",
    "name": "Den",
    "description": "You're in the den.  There's a long desk here with two desktop computers on it.  You can go into the dining room, the living room, or the family room.",
    "actions": [
      {
        "text": "Go to the dining room",
        "ref": "dining_room"
      },
      {
        "text": "Go to the living room",
        "ref": "living_room"
      },
      {
        "text": "Go to the family room",
        "ref": "family_room"
      }
    ]
  },
  {
    "id": "dining_room",
    "name": "Dining Room",
    "description": "You're in the dining room.  It has red wallpaper and a large dining table in the middle of the room.  There is a large window through which you can see the backyard.  There's a door that leads to the backyard.  You can also go to the den, the kitchen, or the main hall",
    "actions": [
      {
        "text": "Go to the main hall",
        "ref": "main_hall"
      },
      {
        "text": "Go to the kitchen",
        "ref": "kitchen"
      },
      {
        "text": "Go to the den",
        "ref": "den"
      },
      {
        "text": "Go outside",
        "ref": "backyard"
      }
    ]
  },
  {
    "id": "downstairs_bathroom",
    "name": "Downstairs Bathroom",
    "description": "You're in the downstairs bathroom.  There's a toilet and a sink here.",
    "actions": [
      {
        "text": "Exit",
        "ref": "front_hall"
      }
    ]
  },
  {
    "id": "driveway",
    "name": "Driveway",
    "description": "You're in the driveway.  There's a garage here with two cars outside it.  You can go to the backyard or into the kitchen through the back door.",
    "actions": [
      {
        "text": "Go to the kitchen",
        "ref": "kitchen"
      },
      {
        "text": "Go in the garage",
        "ref": "garage"
      },
      {
        "text": "Go to the backyard",
        "ref": "backyard"
      }
    ]
  },
  {
    "id": "family_room",
    "name": "Family Room",
    "description": "You're in the family room.  There's a large TV here, and a couch and a recliner in front of it.  There are several game consoles and controllers on the floor.  There's a cabinet next to the TV containing a DVD player and various videos.",
    "actions": [
      {
        "text": "Go to the den",
        "ref": "den"
      }
    ]
  },
  {
    "id": "front_hall",
    "name": "Front Hall",
    "description": "You're in the front hall.  The front door of the house is here.  The entrance to the downstairs bathroom is to the right of the door.  You can also go further inside to the main hall.",
    "actions": [
      {
        "text": "Go outside",
        "ref": "outside_front_door"
      },
      {
        "text": "Go into the bathroom",
        "ref": "downstairs_bathroom"
      },
      {
        "text": "Go further inside",
        "ref": "main_hall"
      }
    ]
  },
  {
    "id": "garage",
    "name": "Garage",
    "description": "You're in the garage.  There's a snowblower here, along with several trash cans and various other junk.  It's big enough for two cars, but there's currently only enough free space for one.",
    "actions": [
      {
        "text": "Go outside",
        "ref": "driveway"
      }
    ]
  },
  {
    "id": "kitchen",
    "name": "Kitchen",
    "description": "You're in the kitchen.  There's a refrigerator, stove, and a counter with a sink here, with shelves and cabinets above them.  There's a dining table on the other side of the room.  You can go out the back door into the driveway, or go to the main hall or the dining room.",
    "actions": [
      {
        "text": "Go outside",
        "ref": "driveway"
      },
      {
        "text": "Go to the main hall",
        "ref": "main_hall"
      },
      {
        "text": "Go to the dining room",
        "ref": "dining_room"
      }
    ]
  },
  {
    "id": "living_room",
    "name": "Living Room",
    "description": "You're in the living room.  There is a couch and several chairs here.  There's a stereo system on one wall, with a record player and a shelf containing an extensive record collection.",
    "actions": [
      {
        "text": "Go to the den",
        "ref": "den"
      },
      {
        "text": "Go to the main hall",
        "ref": "main_hall"
      }
    ]
  },
  {
    "id": "main_hall",
    "name": "Main Hall",
    "description":   "You're in the main hall.  There are stairs that lead to the second floor, as well as entrances to the dining room, kitchen room, living room, and the front hall.  There's an upright piano, as well as a desk.",
    "actions": [
      {
        "text": "Go to the kitchen",
        "ref": "kitchen"
      },
      {
        "text": "Go to the living room",
        "ref": "living_room"
      },
      {
        "text": "Go to the dining room",
        "ref": "dining_room"
      }
    ]
  },
  {
    "id": "outside_front_door",
    "name": "Outside the House",
    "description": "You are standing outside the front door of the house.",
    "actions": [
      {
        "text": "Go inside",
        "ref": "front_hall"
      }
    ]
  },
  {
    "id": "shed",
    "name": "Shed",
    "description": "You're in the shed.  It's stuffed with assorted outdoor toys, such as frisbees and various types of ball.",
    "actions": [
      {
        "text": "Go outside",
        "ref": "backyard"
      }
    ]
  }
]
