=== jwbutler/cyoa/src/types/schemas/Scene.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "Scene.schema.json",
  "type": "object",
  "description": "A particular scene in the game, either a room or a standalone decision tree",
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique identifier for this scene"
    },
    "name": {
      "type": "string",
      "description": "Header text for the room to be displayed in-game"
    },
    "description": {
      "type": "string",
      "description": "Descriptive text for the room to be displayed in-game"
    },
    "actions": {
      "type": "array",
      "description": "Actions that are available unconditionally",
      "items": {
        "$ref": "Action.schema.json"
      }
    },
    "conditions": {
      "type": "array",
      "description": "Actions and descriptions that are available unconditionally",
      "items": {
        "$ref": "Condition.schema.json"
      }
    }
  },
  "required": ["id", "name"],
  "additionalProperties": false
}

=== jwbutler/cyoa/src/scenes.json
[
  {
    "id": "backyard",
    "name": "Backyard",
    "description": "You're in the backyard.  There's a swing set on one end of the yard, and a small shed on another side.",
    "actions": [
      {
        "text": "Go back in the house",
        "scene": "dining_room"
      },
      {
        "text": "Go to the driveway",
        "scene": "driveway"
      },
      {
        "text": "Go in the shed",
        "scene": "shed"
      }
    ]
  },
  {
    "id": "basement",
    "name": "Basement",
    "description": "YOU WIN!",
    "actions": [
      {
        "text": "Restart",
        "scene": "outside_front_door"
      }
    ]
  },
  {
    "id": "basement_stairs",
    "name": "Basement",
    "description": "You open the door to the basement.  There are thick vines here blocking your way!",
    "actions": [
      {
        "text": "Back",
        "scene": "kitchen"
      }
    ],
    "conditions": [
      {
        "forbids": {
          "items": ["axe"]
        }
      },
      {
        "requires": {
          "items": ["axe"]
        },
        "actions": [
          {
            "text": "Cut them with your axe",
            "type": "action",
            "scene": "basement"
          }
        ]
      }
    ]
  },
  {
    "id": "den",
    "name": "Den",
    "description": "You're in the den.  There's a long desk here with two desktop computers on it.  You can go into the dining room, the living room, or the family room.",
    "actions": [
      {
        "text": "Go to the dining room",
        "scene": "dining_room"
      },
      {
        "text": "Go to the living room",
        "scene": "living_room"
      },
      {
        "text": "Go to the family room",
        "scene": "family_room"
      }
    ]
  },
  {
    "id": "dining_room",
    "name": "Dining Room",
    "description": "You're in the dining room.  It has red wallpaper and a large dining table in the middle of the room.  There is a large window through which you can see the backyard.  There's a door that leads to the backyard.  You can also go to the den, the kitchen, or the main hall",
    "actions": [
      {
        "text": "Go to the main hall",
        "scene": "main_hall"
      },
      {
        "text": "Go to the kitchen",
        "scene": "kitchen"
      },
      {
        "text": "Go to the den",
        "scene": "den"
      },
      {
        "text": "Go outside",
        "scene": "backyard"
      }
    ]
  },
  {
    "id": "downstairs_bathroom",
    "name": "Downstairs Bathroom",
    "description": "You're in the downstairs bathroom.  There's a toilet and a sink here.",
    "actions": [
      {
        "text": "Exit",
        "scene": "front_hall"
      }
    ]
  },
  {
    "id": "driveway",
    "name": "Driveway",
    "description": "You're in the driveway.  There's a garage here with two cars outside it.  You can go to the backyard or into the kitchen through the back door.",
    "actions": [
      {
        "text": "Go to the kitchen",
        "scene": "kitchen"
      },
      {
        "text": "Go in the garage",
        "scene": "garage"
      },
      {
        "text": "Go to the backyard",
        "scene": "backyard"
      }
    ]
  },
  {
    "id": "family_room",
    "name": "Family Room",
    "description": "You're in the family room.  There's a large TV here, and a couch and a recliner in front of it.  There are several game consoles and controllers on the floor.  There's a cabinet next to the TV containing a DVD player and various videos.",
    "actions": [
      {
        "text": "Go to the den",
        "scene": "den"
      }
    ]
  },
  {
    "id": "front_hall",
    "name": "Front Hall",
    "description": "You're in the front hall.  The front door of the house is here.  The entrance to the downstairs bathroom is to the right of the door.  You can also go further inside to the main hall.",
    "actions": [
      {
        "text": "Go outside",
        "scene": "outside_front_door"
      },
      {
        "text": "Go into the bathroom",
        "scene": "downstairs_bathroom"
      },
      {
        "text": "Go to the main hall",
        "scene": "main_hall"
      }
    ]
  },
  {
    "id": "garage",
    "name": "Garage",
    "description": "You're in the garage.  There's a snowblower here, along with several trash cans and various other junk.  It's big enough for two cars, but there's currently only enough free space for one.",
    "actions": [
      {
        "text": "Go outside",
        "scene": "driveway"
      }
    ]
  },
  {
    "id": "kitchen",
    "name": "Kitchen",
    "description": "You're in the kitchen.  There's a refrigerator, stove, and a counter with a sink here, with shelves and cabinets above them.  There's a dining table on the other side of the room.  You can go out the back door into the driveway, or go to the main hall or the dining room.  You can also enter the basement.",
    "actions": [
      {
        "text": "Go outside",
        "scene": "driveway"
      },
      {
        "text": "Go to the main hall",
        "scene": "main_hall"
      },
      {
        "text": "Go to the dining room",
        "scene": "dining_room"
      },
      {
        "text": "Check the counter drawer",
        "scene": "kitchen_counter_drawer"
      },
      {
        "text": "Enter the basement",
        "scene": "basement_stairs"
      }
    ]
  },
  {
    "id": "kitchen_counter_drawer",
    "name": "Drawer",
    "actions": [
      {
        "text": "Back",
        "scene": "kitchen"
      }
    ],
    "conditions": [
      {
        "forbids": {
          "items": ["shed_key"]
        },
        "description": "There's a bunch of junk in here.  You notice a key in the drawer.",
        "actions": [
          {
            "text": "Take the key!",
            "type": "item",
            "scene": "kitchen_counter_drawer_key",
            "adds": {
              "items": ["shed_key"]
            }
          }
        ]
      },
      {
        "requires": {
          "items": ["shed_key"]
        },
        "description": "There's nothing in here but junk."
      }
    ]
  },
  {
    "id": "kitchen_counter_drawer_key",
    "name": "Drawer",
    "description": "You take the key and put it in your pocket.",
    "actions": [
      {
        "text": "Back",
        "scene": "kitchen"
      }
    ]
  },
  {
    "id": "living_room",
    "name": "Living Room",
    "description": "You're in the living room.  There is a couch and several chairs here.  There's a stereo system on one wall, with a record player and a shelf containing an extensive record collection.",
    "actions": [
      {
        "text": "Go to the den",
        "scene": "den"
      },
      {
        "text": "Go to the main hall",
        "scene": "main_hall"
      }
    ]
  },
  {
    "id": "main_hall",
    "name": "Main Hall",
    "description":   "You're in the main hall.  There are stairs that lead to the second floor, as well as entrances to the dining room, kitchen room, living room, and the front hall.  There's an upright piano, as well as a desk.",
    "actions": [
      {
        "text": "Go to the kitchen",
        "scene": "kitchen"
      },
      {
        "text": "Go to the living room",
        "scene": "living_room"
      },
      {
        "text": "Go to the dining room",
        "scene": "dining_room"
      },
      {
        "text": "Go to the front hall",
        "scene": "front_hall"
      }
    ]
  },
  {
    "id": "outside_front_door",
    "name": "Outside the House",
    "description": "You are standing outside the front door of the house.",
    "actions": [
      {
        "text": "Go inside",
        "scene": "front_hall"
      }
    ]
  },
  {
    "id": "shed",
    "name": "Shed",
    "actions": [
      {
        "text": "Go outside",
        "scene": "backyard"
      }
    ],
    "conditions": [
      {
        "forbids": {
          "items": ["shed_key"]
        },
        "description": "It's locked.  Maybe there's a key somewhere..."
      },
      {
        "forbids": {
          "items": ["axe"],
          "visited": ["basement_stairs"]
        },
        "requires": {
          "items": ["shed_key"]
        },
        "description": "You're in the shed.  There's a workbench here with a variety of tools."
      },
      {
        "forbids": {
          "items": ["axe"]
        },
        "requires": {
          "items": ["shed_key"],
          "visited": ["basement_stairs"]
        },
        "description": "You're in the shed.  There's a workbench here with a variety of tools, including an axe.",
        "actions": [
          {
            "text": "Take the axe!",
            "type": "item",
            "scene": "shed",
            "adds": {
              "items": ["axe"]
            }
          }
        ]
      },
      {
        "requires": {
          "items": ["axe", "shed_key"]
        },
        "description": "You're in the shed.  It's stuffed with assorted outdoor toys, such as frisbees and various types of ball."
      }
    ]
  },
  {
    "id": "shed_axe",
    "name": "Shed",
    "description": "You take the axe.  It looks a bit rusty, but fairly sharp.  It feels heavy in your hand.",
    "actions": [
      {
        "text": "Back",
        "scene": "shed"
      }
    ]
  }
]
